prog = _{ SOI ~ ((asgmt | expr) ~ ("\n") ?) + ~ EOI }

ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
number = @{ "-" ? ~ ASCII_DIGIT+ }

expr = { term ~ (ops ~ term) * }
term = { ident | number | "(" ~ expr ~ ")" }
asgmt = { "let" ~ ident ~ "=" ~ expr }

ops = _{ add | sub | mul | div | modu | pow }
add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }
modu = { "%" }
pow = { "^" }

WHITESPACE = _{ " " | "\t" }
